# Generated by Django 3.2.3 on 2021-05-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face', models.ImageField(upload_to='videos/')),
                ('audio', models.ImageField(upload_to='videos/')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
