# Generated by Django 3.2.3 on 2021-05-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210524_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='audio',
            field=models.FileField(upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='face',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
